sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1
    - php: 7.1
      env:
        - PHPCS=1

before_script: .travis/before-script.sh
script: .travis/script.sh
after_success: .travis/after-success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: UbWCzOYDqLB92Me90Ny/NfRTn0C17/Q1w3Osm5Cxlqaz2WE0/DiJVPvNcK8gDvyQx4HN+v8XerQU+HX1Lx7YqaZAYYq1OiAwXvqpzovxEV5n38D95LnaXM8RmX2UbNBlmnaraF2INaounmhErWc9nA0022gwBG9TueOTFVuiDmk=
