language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.3
      env:
        - COVERALLS=1
    - php: 5.3
      env:
        - PHPCS=1

before_script:
  - test/before-script.sh

script:
  - test/script.sh

after_success:
  - test/after-success.sh

notifications:
  email: false
